INSERT INTO attivita_report (id_attivita, id_account_club, nome_club_sponsor, titolo, descrizione, stato, rapporto_completo, livello_attivita, causa, tipo_progetto, attivita_distintiva, finanziata_lcif, data_inizio, data_conclusione, persone_servite, persone_servite_limite, totale_volontari, totale_ore_servizio, totale_ore_servizio_capped, alberi_piantati, valuta_fondi_donati, totale_fondi_donati, fondi_donati_usd_capped, donazione_lcif, organizzazione_beneficiata, valuta_fondi_raccolti, totale_fondi_raccolti, fondi_raccolti_usd_capped, creato_da) VALUES
('SA-09508045', '001Ns00000EDgRMIA1', 'ALTA MAREMMA', 'Congresso Distretto 108 La', 'I delegati Puggelli, Bernardini e Aguggeri hanno partecipato a Firenze al Congresso del nostro Distretto', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-05-16', '2026-05-16', NULL, 0, 3, 24.00, 24.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Maurizio Spagnesi'),
('SA-09565254', '001Ns00000EDgRMIA1', 'ALTA MAREMMA', 'Riunione di Circoscrizione', 'Riunione di Circoscrizione presso lo Stabilimento Balneare Valbona di Castiglione della Pescaia.', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-05-30', '2026-05-30', NULL, 0, 6, 24.00, 24.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Maurizio Spagnesi'),
('SA-09565292', '001Ns00000EDgRMIA1', 'ALTA MAREMMA', 'Codice Rosa', 'Contributo al Service "Codice Rosa"', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Donazione', FALSE, FALSE, '2026-06-01', '2026-06-01', NULL, 0, NULL, NULL, 0.00, NULL, 'EUR', 400.00, 465.44, 0, 'Codice Rosa', NULL, NULL, 0.00, 'Maurizio Spagnesi'),
('SA-09565312', '001Ns00000EDgRMIA1', 'ALTA MAREMMA', 'Disabilità "Ass. Biglie Sciolte"', 'Incontro ed offerta di una giornata in piscina e parco giochi all''Associazione "Biglie Sciolte", genitori che si occupano dei bambini autistici.
Presente la Presidente dell''Associazione Elena Chelotti e l''Assessore al Sociale del Comune di Follonica Sandro Marrini.', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Altro', FALSE, FALSE, '2026-05-31', '2026-05-31', 20, 20, 17, 51.00, 51.00, NULL, 'EUR', 750.00, 878.47, 0, 'Biglie Sciolte', NULL, NULL, 0.00, 'Maurizio Spagnesi'),
('SA-09565358', '001Ns00000EDgRMIA1', 'ALTA MAREMMA', 'Massadotta', 'Attività di Direttore Sanitario e di Psicologo dei soci Spagnesi ed Aguggeri presso l''ambulatorio onlus di Massadotta', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Attività per altri servizi sanitari', FALSE, FALSE, '2026-05-04', '2026-05-29', 20, 20, 2, 24.00, 24.00, NULL, 'EUR', 3000.00, 3513.87, 0, 'Massadotta', 'EUR', 3000.00, 3513.87, 'Maurizio Spagnesi'),
('SA-09559423', '001Ns00000EDgRMIA1', 'ANTICHE VALLI LUCCHESI', 'Laboratorio Disabilità Comune di Capannori (LU)', 'Contributo alla creazione di un laboratorio per disabili in collaborazione con il Comune di Capannori (LU)', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Evento comunitario', FALSE, FALSE, '2026-02-20', '2026-02-20', 40, 40, 5, 10.00, 10.00, NULL, 'EUR', 1500.00, 1789.83, 0, 'Comune di Capannori (LU)', 'EUR', 1500.00, 1789.83, 'Antonio Tonelli'),
('SA-09509360', '001Ns00000EDgRMIA1', 'Arezzo Chimera', 'Partecipazione Consiglio Multidistretto Leo 108 Italy', 'partecipazione al consiglio del Multidistretto Leo 108 Italy con versamento per cena di gala del sabato', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-02-21', '2026-02-21', NULL, 0, 1, 4.00, 4.00, NULL, 'USD', 50.00, 50.00, 0, NULL, NULL, NULL, 0.00, 'Giacomo Martini'),
('SA-09581710', '001Ns00000EDgRMIA1', 'Arezzo Chimera', 'Presenza alla installazione di un DAE a Vogognano LC Casentino', 'Presenza alla installazione del DAE presso la chiesa di Santa Maria della Neve a Vogognano comune di Subbiano da parte del LC Casentino.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Attività per altri servizi sanitari', FALSE, FALSE, '2026-05-17', '2026-05-17', 40, 40, 2, 3.00, 3.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Giuseppina Violetti'),
('SA-09581844', '001Ns00000EDgRMIA1', 'Arezzo Chimera', 'II Assemblea Soci 2025/2026', 'L''assemblea soci si è riunita per la discussione del presente Ordine del Giorno: 
- Elezione Officers Annata Lionistica 2026/2027,
- Discussione sull?ingresso del Club nel Terzo Settore;
- Nomina delegati alla Convention Distrettuale ed alla Multidistrettuale.
- Acquisto dispositivi audio e video per il Club.
- Varie ed eventuali.', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-04-16', '2026-04-16', NULL, 0, 17, 51.00, 51.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Giuseppina Violetti'),
('SA-09502829', '001Ns00000EDgRMIA1', 'CASENTINO', 'CONCORSO UN POSTER PER LA PACE', 'Premiazione alla scuola I.C.S. G.GARIBALDI  ? CAPOLONA SUBBIANO - PREMIAZIONE CLASSI TERZE', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Concorso Un Poster per la Pace e Concorso di saggistica', TRUE, FALSE, '2026-05-20', '2026-05-20', 24, 24, 6, 6.00, 6.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09518865', '001Ns00000EDgRMIA1', 'CASENTINO', 'TRE DAE PER IL CUORE DEL CASENTINO - CONSEGNA CHIESA DI VOGOGNANO IN SUBBIANO', 'La donazione del Defibrillatore Automatico Esterno (DAE) alla Chiesa di Vogognano rappresenta un importante gesto di attenzione verso la salute e la sicurezza della comunità locale.
Il dispositivo sarà installato in un punto strategico del paese, facilmente accessibile in caso di emergenza, con l?obiettivo di garantire un intervento rapido nelle situazioni di arresto cardiaco improvviso.
La disponibilità di un DAE sul territorio costituisce oggi uno strumento fondamentale di prevenzione e protezione della vita.
L?iniziativa nasce grazie alla collaborazione tra:
LC Casentino, promotore e donatore del dispositivo;
la comunità parrocchiale di Vogognano;
la Misericordia di Subbiano, che si occuperà della gestione del DAE.
Questo progetto dimostra come la collaborazione tra associazioni, volontariato e territorio possa creare valore concreto per i cittadini.
La gestione del defibrillatore sarà affidata alla Misericordia di Subbiano, realtà da sempre impegnata nel soccorso sanitario e nell?assistenza alla popolazione. 
L?associazione garantirà:
il controllo periodico del dispositivo;
la manutenzione e l?efficienza operativa del DAE;
il coordinamento delle attività legate alla formazione BLSD;
la promozione della cultura del primo soccorso sul territorio.

Ogni minuto è determinante in caso di arresto cardiaco.
La presenza di un defibrillatore accessibile sul territorio può aumentare in maniera significativa le probabilità di sopravvivenza.
Per questo motivo, la diffusione dei DAE rappresenta:
un investimento nella salute pubblica;
un segnale di responsabilità sociale;
un esempio concreto di prevenzione sanitaria.
La sensibilizzazione dei cittadini e la formazione all?utilizzo del defibrillatore sono elementi fondamentali per rendere il territorio sempre più sicuro e preparato.
Un gesto di solidarietà verso il territorio
La donazione del DAE alla Chiesa di Vogognano non è soltanto un atto simbolico, ma un contributo concreto al benessere della collettività.
Attraverso questa iniziativa si rafforza il senso di comunità e di vicinanza alle persone, valorizzando il ruolo del volontariato e dell?impegno civile.

La presenza del dispositivo rappresenterà un punto di riferimento importante per residenti, famiglie, anziani e visitatori del territorio.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Donazione', FALSE, FALSE, '2026-05-17', '2026-05-17', 1000, 1000, 6, 60.00, 60.00, NULL, 'EUR', 2000.00, 2342.58, 0, 'Comunità di Vogonano in Subbiano', NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09518911', '001Ns00000EDgRMIA1', 'CASENTINO', 'TRE DAE PER IL CUORE DEL CASENTINO - CONSEGNA PIAZZA GRANDE IN BIBBIENA', 'La donazione del Defibrillatore Automatico Esterno (DAE) all?Associazione ?Amici per Bibbiena? rappresenta un importante intervento a favore della sicurezza pubblica e della tutela della salute dei cittadini. Il dispositivo sarà installato in Piazza Grande, uno dei luoghi più rappresentativi e frequentati del centro storico di Bibbiena, punto di incontro della vita sociale, culturale e comunitaria della città.
La presenza di un DAE accessibile al pubblico costituisce oggi uno strumento fondamentale per intervenire tempestivamente in caso di arresto cardiaco improvviso. L?iniziativa è stata resa possibile grazie alla generosa donazione del LC Casentino, da sempre impegnato nella promozione di progetti sociali, sanitari e di servizio al territorio. Attraverso questa donazione, il LC Casentino conferma la propria attenzione verso il benessere della comunità e la diffusione della cultura della prevenzione.
Il progetto rappresenta un esempio concreto di solidarietà e collaborazione tra associazioni e cittadini, con l?obiettivo comune di rendere il territorio sempre più sicuro e attento alle emergenze sanitarie.
L?installazione del dispositivo contribuirà a:
aumentare la sicurezza nelle aree pubbliche;
garantire un presidio sanitario accessibile nel centro storico;
sensibilizzare cittadini e visitatori sull?importanza del primo soccorso;
promuovere la cultura della prevenzione e della responsabilità collettiva.
Piazza Grande: un luogo simbolico
Piazza Grande rappresenta il cuore storico e sociale di Bibbiena.
È un luogo di incontro, eventi, manifestazioni e aggregazione quotidiana per residenti e visitatori.
La scelta di installare il DAE proprio in questo spazio nasce dalla volontà di garantire una maggiore copertura del territorio in una zona particolarmente frequentata.
La rapidità di intervento nei primi minuti di un?emergenza cardiaca può fare la differenza tra la vita e la morte.
Per questo motivo, la presenza di un defibrillatore in un luogo centrale assume un valore fondamentale per tutta la collettività.
La diffusione dei DAE sul territorio rappresenta oggi una delle più importanti forme di prevenzione sanitaria.
Ogni anno molte vite possono essere salvate grazie a:
un intervento tempestivo;
la disponibilità di dispositivi salvavita;
la formazione dei cittadini alle manovre di primo soccorso.
Questa iniziativa vuole essere anche un messaggio di sensibilizzazione verso l?importanza della sicurezza pubblica e della partecipazione attiva della comunità.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Donazione', FALSE, FALSE, '2026-05-23', '2026-05-23', 400, 400, 6, 60.00, 60.00, NULL, 'EUR', 2000.00, 2342.58, 0, 'Comunità di Vogonano in Subbiano', NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09518944', '001Ns00000EDgRMIA1', 'CASENTINO', 'LIONS IN PIAZZA 2025', 'Il Centro commerciale ?Il Casentino? di Bibbiena vedrà ancora una volta protagonista il Lions Club di vallata con l?ormai tradizionale appuntamento con il ?Lions in piazza?. 
La manifestazione si avvarrà, quest?anno, della preziosa collaborazione della Misericordia di Bibbiena, dell?azienda ESAOTE, uno dei leader mondiali nella diagnostica per immagini: produzione di ecografi, sistemi di risonanza magnetica e software IT per la sanità, e del Centro Commerciale ?Il Casentino?, nonché il patrocinio dei comuni di Poppi, Bibbiena, Pratovecchio Stia, Castel S. Niccolò e Castel Focognano, dell?0rdine provinciale dei medici, dell?azienda USL Toscana Sud-Est e di ISPRO (Istituto per lo Studio, la Prevenzione e la Rete Oncologica). 
Per tutta la giornata di sabato 23 maggio, a partire dalle ore 9,30, medici specialisti si alterneranno nei mezzi mobili messi a disposizione dalla locale Misericordia per offrire gratuitamente consulenza e consigli pratici per numerose specialità. Nella giornata si terranno anche dimostrazioni di primo soccorso pediatrico e di BLSD a cura del centro di formazione della Misericordia di Bibbiena.
Nel corso della mattinata ci sarà anche la consegna di un DAE alla comunità di Bibbiena donato dai Lions nell?ambito di un vasto progetto con cui il Lions Club Casentino donerà 5 postazioni DAE in altrettanti centri strategici casentinesi. 
Con la consulenza dei medici specialisti il Lions Club Casentino, presieduto da Massimiliano Brogi, permetterà a molti cittadini di imparare le principali norme di prevenzione, diagnosi e cura, di valutare il proprio stato di salute e, qualora ve ne sia bisogno, di intervenire. 
?Prevenire prima di curare?, con questo slogan il Lions Club Casentino dà, dunque, appuntamento presso il Centro commerciale ?Il Casentino? di Bibbiena che anche in questa edizione, con grande sensibilità e senso civico, come negli anni passati, ha messo a disposizione del Lions Club locale i propri spazi esterni.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Attività per altri servizi sanitari', TRUE, FALSE, '2026-05-23', '2026-05-23', 483, 483, 45, 500.00, 500.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09607741', '001Ns00000EDgRMIA1', 'CASENTINO', 'Giotto e San Francesco. Una rivoluzione nell''Umbria del Trecento a Perugia', 'Mostra  ?Giotto e San Francesco. Una rivoluzione nell''Umbria del Trecento" a Perugia presso la Galleria Nazionale dell''Umbria - Palazzo dei Priori.', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-05-30', '2026-05-30', NULL, 0, 20, 40.00, 40.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09611408', '001Ns00000EDgRMIA1', 'CASENTINO', 'CONCORSO UN POSTER PER LA PACE', 'Premiazione alla scuola I.C.S. ?BERNARDO DOVIZI? ? Bibbiena', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Concorso Un Poster per la Pace e Concorso di saggistica', TRUE, FALSE, '2026-06-04', '2026-06-04', 25, 25, 6, 6.00, 6.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09611556', '001Ns00000EDgRMIA1', 'CASENTINO', 'CONCORSO UN POSTER PER LA PACE', 'Premiazione alla scuola I.C.S. ?BERNARDO DOVIZI? ? Bibbiena Premiazione Vincitrice Ekasmeet Kaur - MERITO ARTISTICO -', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Concorso Un Poster per la Pace e Concorso di saggistica', TRUE, FALSE, '2026-06-08', '2026-06-08', 25, 25, 5, 10.00, 10.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09611606', '001Ns00000EDgRMIA1', 'CASENTINO', 'CONCORSO UN POSTER PER LA PACE', 'Premiazione alla scuola Istituto Comprensivo Statale Poppi', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Concorso Un Poster per la Pace e Concorso di saggistica', TRUE, FALSE, '2026-06-05', '2026-06-05', 24, 24, 6, 6.00, 6.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09611616', '001Ns00000EDgRMIA1', 'CASENTINO', 'DONAZIONE STRUMENTI MUSICALI SCUOLA DI STIA', 'Concerto presso I.C.S. Alto Casentino ? Scuola di Pratovecchio Stia con gli strumenti musicali donati in collaborazione con il ROTARY CLLUB CASENTINO e FIDAPA', 'Comunicato', TRUE, 'Lions Club', 'Giovani', 'Donazione', FALSE, FALSE, '2026-06-04', '2026-06-04', 60, 60, 6, 30.00, 30.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Antonio de Bari'),
('SA-09487818', '001Ns00000EDgRMIA1', 'CASTIGLIONE DELLA PESCAIA "SALEBRUM"', 'Aiuola Melvin Jones', 'Rifacimento dell''aiuola sita in Piazza Orsino Orsini in Castiglione della Pescaia, nominata con il nome del fondatore della nostra Associazione.', 'Comunicato', TRUE, 'Lions Club', 'Ambiente', 'Messa a dimora e cura di alberi', FALSE, FALSE, '2026-04-23', '2026-04-23', 120, 120, 14, 70.00, 70.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Roberto Breschi'),
('SA-09487858', '001Ns00000EDgRMIA1', 'CASTIGLIONE DELLA PESCAIA "SALEBRUM"', 'Charter e Visita del Governatore', 'In occasione della Charte e Visita del Governatore donati a  ISPRO, Istituto per lo Studio, la Prevenzione e la Rete Oncologica ? 1000,00.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Donazione', FALSE, FALSE, '2026-04-24', '2026-04-24', 120, 120, 120, 60.00, 60.00, NULL, 'EUR', 1000.00, 1154.22, 0, 'IISPRO Istituto per lo Studio, la Prevenzione e la Rete Oncologica', NULL, NULL, 0.00, 'Roberto Breschi'),
('SA-09487907', '001Ns00000EDgRMIA1', 'CASTIGLIONE DELLA PESCAIA "SALEBRUM"', 'Gli Etruschi a occhi chiusi', 'Iniziatica organizzata dal Lions Club Castiglione della Pescaia Salebrum in collaborazione con Leo Club Francesco Iannitelli, la Unione Italiana Ciechi e Ipovedenti, il Muvet-Museo Civico Archeologico Isidoro Falchi, con il patrocinio dell''Amministrazione Comunale di Castiglione della Pescaia.', 'Comunicato', TRUE, 'Lions Club', 'Vista', 'Servizi di assistenza per non vedenti e ipovedenti', FALSE, FALSE, '2026-05-16', '2026-05-16', 85, 85, 30, 60.00, 60.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Roberto Breschi'),
('SA-09487952', '001Ns00000EDgRMIA1', 'CASTIGLIONE DELLA PESCAIA "SALEBRUM"', 'Interconnettiamoci...ma con la testa', 'Service di rilevanza nazionale che il Salebrum ha svolto per le lassi quarta e quinta della Scuola Primaria di Castiglione della Pescaia. Ha svolto la lezione Pietro Fontana, Ingegnere Elettronico specializzato n sicurezza informatica e Governatore eletto del Distretto 108La per l''''anno lionistico 2026/2027.', 'Comunicato', TRUE, 'Lions Club', 'Altro servizio umanitario', 'Sensibilizzazione e istruzione e advocacy', FALSE, FALSE, '2026-05-18', '2026-05-18', 60, 60, 5, 15.00, 15.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Roberto Breschi'),
('SA-09487999', '001Ns00000EDgRMIA1', 'CASTIGLIONE DELLA PESCAIA "SALEBRUM"', 'Congresso Distrettuale', 'Congresso Distrettuale a Firenze Radisson Blu Hotel Florence. Cinque delegati più due Soci del Salebrum supplenti hanno partecipato.', 'Comunicato', TRUE, 'Lions Club', 'Amministrazione', 'Attività di rafforzamento del club', FALSE, FALSE, '2026-05-16', '2026-05-16', NULL, 0, 7, 70.00, 70.00, NULL, NULL, NULL, 0.00, 0, NULL, NULL, NULL, 0.00, 'Roberto Breschi')
ON CONFLICT (id_attivita) DO UPDATE SET
  id_account_club=EXCLUDED.id_account_club, nome_club_sponsor=EXCLUDED.nome_club_sponsor, titolo=EXCLUDED.titolo, descrizione=EXCLUDED.descrizione, stato=EXCLUDED.stato, rapporto_completo=EXCLUDED.rapporto_completo, livello_attivita=EXCLUDED.livello_attivita, causa=EXCLUDED.causa, tipo_progetto=EXCLUDED.tipo_progetto, attivita_distintiva=EXCLUDED.attivita_distintiva, finanziata_lcif=EXCLUDED.finanziata_lcif, data_inizio=EXCLUDED.data_inizio, data_conclusione=EXCLUDED.data_conclusione, persone_servite=EXCLUDED.persone_servite, persone_servite_limite=EXCLUDED.persone_servite_limite, totale_volontari=EXCLUDED.totale_volontari, totale_ore_servizio=EXCLUDED.totale_ore_servizio, totale_ore_servizio_capped=EXCLUDED.totale_ore_servizio_capped, alberi_piantati=EXCLUDED.alberi_piantati, valuta_fondi_donati=EXCLUDED.valuta_fondi_donati, totale_fondi_donati=EXCLUDED.totale_fondi_donati, fondi_donati_usd_capped=EXCLUDED.fondi_donati_usd_capped, donazione_lcif=EXCLUDED.donazione_lcif, organizzazione_beneficiata=EXCLUDED.organizzazione_beneficiata, valuta_fondi_raccolti=EXCLUDED.valuta_fondi_raccolti, totale_fondi_raccolti=EXCLUDED.totale_fondi_raccolti, fondi_raccolti_usd_capped=EXCLUDED.fondi_raccolti_usd_capped, creato_da=EXCLUDED.creato_da;